resources:
  - name: grafana
    type: containerservice
    attributes: 
      containers:
        - image: grafana/grafana:latest
          profile: run
          ports:
            - internal: 3000
              external: 3000
              schema: http